#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [2]

sde:
  max_sigma: 30
  T: 400
  schedule: cosine
  eps: 0.005

degradation:
  mask_root: your mask path
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: GT
    dataroot_GT: your image path

    use_shuffle: true
    n_workers: 4
    batch_size: 16
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 8000000
  warmup_iter: -1  # no warm up
  lr_steps: [2000000, 4000000, 6000000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
